### PR TITLE
3084 support Rails 4.1

### PR DESCRIPTION
**Pull request by baburdick**
Task 3084; and see HornsAndHooves#2

### CODE REVIEW

**Comment by baburdick** [comment]
Next problem:
```
Failures:

  1) Moribus Tracked should set is_current record to false for superseded record
     Failure/Error: @info.update_attributes(:spec_person_name_id => 2)
     ArgumentError:
       wrong number of arguments (1 for 2)
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/sanitization.rb:6:in `quote_value'
     # ./lib/moribus/tracked_behavior.rb:83:in `current_to_false_sql_statement'
     # ./lib/moribus/tracked_behavior.rb:52:in `update_current'
     # ./lib/moribus/tracked_behavior.rb:32:in `tracked_save_callback'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:424:in `block in make_lambda'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:298:in `call'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:298:in `block in halting'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `call'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `call'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:166:in `block in halting'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:215:in `call'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:86:in `call'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activesupport-4.1.9/lib/active_support/callbacks.rb:86:in `run_callbacks'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/callbacks.rb:302:in `create_or_update'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/persistence.rb:103:in `save'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/validations.rb:51:in `save'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/attribute_methods/dirty.rb:21:in `save'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/transactions.rb:268:in `block (2 levels) in save'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/transactions.rb:208:in `transaction'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/transactions.rb:268:in `block in save'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/transactions.rb:267:in `save'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/persistence.rb:232:in `block in update'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/transactions.rb:208:in `transaction'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
     # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/persistence.rb:230:in `update'
     # ./spec/moribus_spec.rb:206:in `block (3 levels) in <top (required)>'
```

**Comment by baburdick** [comment]
So `klass.quote_value(false) ` needs another argument (https://github.com/HornsAndHooves/moribus/blob/master/lib/moribus/tracked_behavior.rb#L83).

**Comment by baburdick** [comment]
Remaining failures:
```
Failures:

  1) Moribus::AliasAssociation reflection aliasing alias association name in reflections
     Failure/Error: SpecPost.reflect_on_association(:author).should_not be_nil
       expected: not nil
            got: nil
     # ./spec/moribus/alias_association_spec.rb:41:in `block (3 levels) in <top (required)>'

  2) Moribus::AliasAssociation reflection aliasing should not raise error when using aliased name in scopes
     Failure/Error: expect{
       expected no Exception, got #<ActiveRecord::AssociationNotFoundError: Association named 'comments' was not found on SpecPost; perhaps you misspelled it?> with backtrace:
         # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/associations.rb:154:in `association'
         # ./lib/moribus/extensions.rb:25:in `association'
         # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/associations/preloader.rb:147:in `block in grouped_records'
         # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/associations/preloader.rb:145:in `each'
         # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/associations/preloader.rb:145:in `grouped_records'
         # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/associations/preloader.rb:134:in `preloaders_for_one'
         # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/associations/preloader.rb:106:in `preloaders_on'
         # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/associations/preloader.rb:94:in `block in preload'
         # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/associations/preloader.rb:93:in `each'
         # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/associations/preloader.rb:93:in `flat_map'
         # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/associations/preloader.rb:93:in `preload'
         # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/relation.rb:617:in `block in exec_queries'
         # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/relation.rb:616:in `each'
         # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/relation.rb:616:in `exec_queries'
         # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/relation.rb:493:in `load'
         # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/relation.rb:238:in `to_a'
         # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/relation/finder_methods.rb:474:in `find_nth_with_limit'
         # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/relation/finder_methods.rb:468:in `find_nth'
         # /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activerecord-4.1.9/lib/active_record/relation/finder_methods.rb:132:in `first'
         # ./spec/moribus/alias_association_spec.rb:46:in `block (4 levels) in <top (required)>'
         # ./spec/moribus/alias_association_spec.rb:45:in `block (3 levels) in <top (required)>'
     # ./spec/moribus/alias_association_spec.rb:45:in `block (3 levels) in <top (required)>'

Deprecation Warnings:

Requiring `rspec/autorun` when running RSpec via the `rspec` command is deprecated. Called from /Users/bruceb/.rvm/gems/ruby-2.1.2@moribus/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'.

Using `should_not` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` instead. Called from /Users/bruceb/Code/OSS/git-repos/HornsAndHooves-moribus/spec/moribus/alias_association_spec.rb:41:in `block (3 levels) in <top (required)>'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

2 deprecation warnings total

Finished in 2.97 seconds (files took 0.94357 seconds to load)
46 examples, 2 failures

Failed examples:

rspec ./spec/moribus/alias_association_spec.rb:40 # Moribus::AliasAssociation reflection aliasing alias association name in reflections
rspec ./spec/moribus/alias_association_spec.rb:44 # Moribus::AliasAssociation reflection aliasing should not raise error when using aliased name in scopes
```

**Comment by baburdick** [comment]
So it looks like association aliases are not getting added to the reflections in Rails 4.1.x:
```ruby
 #4.0.x:
> SpecPost.reflections.keys
#Pry(#<RSpec::ExampleGroups::MoribusAliasAssociation::ReflectionAliasing:0x000001018a6720>):
# => [:spec_author, :creator, :spec_comments, :remarks, :spec_post_info, :information, :author, :comments, :post_info]
```
```ruby
#4.1.x:
> SpecPost.reflections.keys
#Pry(#<RSpec::ExampleGroups::MoribusAliasAssociation::ReflectionAliasing:0x00000106ade6c8>):
# => [:spec_author, :spec_comments, :spec_post_info]
```

**Comment by baburdick** [comment]
This is ready for review and merging. Tests pass. And support for Rails 4.0.x was retained.

**Comment by baburdick** [comment]
@akuzko, @albertosaurus, @greyblake, @romatr, et al.: Do these changes meet your approval?

Note: I think bigger changes will be needed for Rails 4.2.

**Comment by albertosaurus** [comment]
LGTM

**Comment by baburdick** [comment]
Apparently this change introduces lots of `StaleObjectError`s and `"undefined method `type' for "lock_version"` errors in client code. :-(

**Pull request merged**
